version: "3"
services:
  ### nginx ###
  nginx:
    image: nginx:${NGINX_VERSION}
    volumes:
      - ${APPLICATION}:/www
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOGS_PATH}:/wwwlogs
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    links:
      - php-fpm72:php72
      - php-fpm56:php56
    restart: always
    networks:
      - default
  ### php7.2 fpm ###
  php-fpm72:
    build:
      context: ./php72
    volumes:
      - ${APPLICATION}:/www
      - ${PHP72_INI_PATH}:/usr/local/etc/php/php.ini
      - ${PHP72_LOGS_PATH}:/phplogs
    restart: always
    networks:
      - default
    ports:
      - "${PHP72_FPM_PORT}:9000"
    links:
        - redis
        - mysql
### php56 fpm ###
  php-fpm56:
    build:
      context: ./php56
    volumes:
      - ${APPLICATION}:/www
      - ${PHP56_INI_PATH}:/usr/local/etc/php/php.ini
      - ${PHP56_LOGS_PATH}:/phplogs
    restart: always
    networks:
      - default
    ports:
      - "${PHP56_FPM_PORT}:9000"
    links:
        - redis
        - mysql
### mysql ###
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PWD}
    volumes:
      - ${MYSQL_LOGS_PATH}:/logs
      - ${MYSQL_CNF_PATH}:/etc/mysql/my.cnf
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
### redis ###
  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONF_PATH}:/etc/redis.conf
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default
networks:
  default: